# Generated by Django 4.2 on 2024-09-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
    ]
