# Generated by Django 4.2 on 2024-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_remove_content_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
