# Generated by Django 4.2 on 2024-09-03 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_content_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="city",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="user",
            name="type",
        ),
    ]
