# Generated by Django 4.2 on 2024-09-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_city_user_username_remove_user_age_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'content', 'value')},
        ),
    ]
