# Generated by Django 4.2 on 2024-10-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0007_alter_content_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tags",
            name="image",
            field=models.ImageField(default="", max_length=300, upload_to="images_tag"),
            preserve_default=False,
        ),
    ]
