# Generated by Django 4.2 on 2024-10-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_tags_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
