# Generated by Django 4.2 on 2024-10-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_content_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'content')},
        ),
    ]
