# Generated by Django 4.2 on 2024-11-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0013_alter_content_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="contact",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
