# Generated by Django 4.2 on 2025-03-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0020_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="date_end",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="date_start",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=250),
        ),
    ]
